"use strict";
/* =========================================================================
   Career Map v2 — renderer (2026-09-16)

   DATA: ./career.json ONLY, schema_version 2, GENERATED by
   P-resume/tools/career-map-gen from career_map.json. There is no fallback
   file and no sample data on purpose: the old three-way fallback let a
   broken load look like a working page (the 08-28 silent-drop). A load or
   shape problem now shows in #databadge and nothing fictional renders.

   TWO VIEWS in one document — body.view-plain / body.view-map:
     plain = identity · claims · six pattern cards · chronology (default in
             portrait, or ?view=plain, or the header toggle, or key P)
     map   = the mycelium canvas + legend chips (default in landscape)
   The side panel and the question index are shared.

   COLOUR: JSON carries palette TOKEN names (cab-1…cab-4, ink, ink-soft,
   cab-2-dashed); CSS resolves them per scheme, so light/dark is free.
   ?scheme=light|dark sets data-scheme on <html> (also how headless dark
   renders are made).

   GEOMETRY is unchanged from v1: authored pos:[x,y] are bbox-fitted to the
   canvas; portrait transposes the whole layout; nodes without pos fan out
   around their trunk (visibly worse — the generator refuses them by default).
   ========================================================================= */

/* ---------- scheme + view from the URL ---------- */
const PARAMS = new URLSearchParams(location.search);
(function applyScheme(){
  const s = PARAMS.get("scheme");
  if (s === "light" || s === "dark") document.documentElement.dataset.scheme = s;
})();

/* ---------- palette tokens → CSS ---------- */
const TOKENS = new Set(["cab-1","cab-2","cab-3","cab-4","ink","ink-soft"]);
function tokenOf(name){ const base = String(name||"ink").replace(/-dashed$/,""); return TOKENS.has(base) ? base : "ink"; }
function cssColor(name){ return `var(--${tokenOf(name)})`; }
const isDashed = (name) => /-dashed$/.test(String(name||""));

/* ---------- shapes ---------- */
const CAPS = [
  (r)=>`M ${-r} 0 Q ${-r} ${-r*1.1} 0 ${-r*1.1} Q ${r} ${-r*1.1} ${r} 0 Z`,
  (r)=>`M ${-r*0.9} 0 L 0 ${-r*1.5} L ${r*0.9} 0 Z`,
  (r)=>`M ${-r*1.15} 0 Q ${-r*0.6} ${-r*0.5} 0 ${-r*0.55} Q ${r*0.6} ${-r*0.5} ${r*1.15} 0 Z`,
  (r)=>`M ${-r*0.85} 0 Q ${-r*0.95} ${-r*1.3} 0 ${-r*1.35} Q ${r*0.95} ${-r*1.3} ${r*0.85} 0 Z`,
  (r)=>`M ${-r*1.1} 0 Q ${-r*0.9} ${-r*0.35} ${-r*0.5} ${-r*0.6} Q 0 ${-r*1.0} ${r*0.5} ${-r*0.6} Q ${r*0.9} ${-r*0.35} ${r*1.1} 0 Z`,
  (r)=>`M ${-r*0.55} 0 Q ${-r*0.6} ${-r*1.5} 0 ${-r*1.55} Q ${r*0.6} ${-r*1.5} ${r*0.55} 0 Z`
];

/* ---------- normalize: schema v2 only, loud on anything else ---------- */
function normalize(raw){
  if (!raw || raw.meta?.schema_version !== 2 || !Array.isArray(raw.trunks) || !raw.trunks.length)
    throw new Error("career.json is not schema_version 2 — run tools/career-map-gen/gen.py build");
  const out = { meta: raw.meta, map: raw.map||{}, ui: raw.ui||{}, identity: raw.identity||null,
                trunks: [], throughlines: [], claims: raw.claims||[], decisions: raw.decisions||[],
                chronology: raw.chronology||[] };
  const ids = new Set();
  raw.trunks.forEach((t,ti)=>{
    const nt = { id: String(t.id), name: t.name, trigger: t.trigger||"", color: t.color||"ink", pos: goodPos(t.pos), threads: [] };
    (t.threads||[]).forEach((th,i)=>{
      if (ids.has(th.id)) throw new Error("duplicate node id "+th.id);
      ids.add(th.id);
      nt.threads.push({ id: String(th.id), name: th.name, years: th.years||"", years_full: th.years_full||th.years||"", trigger: th.trigger||"", detail: th.detail||"",
        plain_line: th.plain_line||"", kind: th.kind||"", employer: th.employer||"", start: th.start||"", end: th.end ?? null,
        pos: goodPos(th.pos), shape: (i % CAPS.length), question_types: th.question_types||[], keywords: th.keywords||[] });
    });
    out.trunks.push(nt);
  });
  (raw.throughlines||[]).forEach((tl,i)=>{
    const nodeIds = (tl.nodeIds||[]).map(String);
    const missing = nodeIds.filter(n => !ids.has(n));
    if (missing.length) throw new Error(`throughline ${tl.id} references unknown node(s): ${missing.join(", ")}`);
    out.throughlines.push({ id: String(tl.id), name: tl.name, trigger: tl.trigger||"", color: tl.color||"ink", nodeIds, plain_reading: tl.plain_reading||"" });
  });
  out.claims.forEach(c => { c.evidence = (c.evidence||[]).filter(e => ids.has(e.node_id)); });
  return out;
}
function goodPos(p){ return (Array.isArray(p)&&p.length===2&&isFinite(p[0])&&isFinite(p[1])) ? p : null; }
const isFrac = (p)=>p[0]>=0&&p[0]<=1&&p[1]>=0&&p[1]<=1;

/* ---------- geometry (orientation-aware, unchanged from v1) ---------- */
let VB={w:1600,h:1000,pad:110}, SCALE=1, ANCHORS=null, isPortrait=false;
const LANDSCAPE_ANCHORS=[[0.24,0.30],[0.22,0.70],[0.52,0.80],[0.80,0.64],[0.76,0.24],[0.50,0.18],[0.50,0.50],[0.05,0.5],[0.95,0.5]];
const PORTRAIT_ANCHORS=[[0.30,0.16],[0.72,0.14],[0.78,0.44],[0.68,0.76],[0.26,0.80],[0.22,0.48],[0.50,0.50],[0.50,0.05],[0.50,0.95]];
function updateMode(){
  isPortrait = window.innerHeight > window.innerWidth*1.15;
  if(isPortrait){ VB={w:1000,h:1600,pad:95}; SCALE=1.35; ANCHORS=PORTRAIT_ANCHORS; }
  else          { VB={w:1600,h:1000,pad:110}; SCALE=1;  ANCHORS=LANDSCAPE_ANCHORS; }
  return isPortrait;
}
updateMode();
const clamp=(v,a,b)=>Math.min(b,Math.max(a,v));

let POS={}, ORIGIN=null, SPORES=[];
function computePositions(data){
  POS={}; ORIGIN=null; SPORES=[];
  const abs=[]; const collect=p=>{ if(p&&!isFrac(p)) abs.push(p); };
  data.trunks.forEach(t=>{ collect(t.pos); t.threads.forEach(th=>collect(th.pos)); });
  const rawOrigin=goodPos(data.map.origin), rawSpores=(data.map.ambientSpores||[]).map(goodPos).filter(Boolean);
  collect(rawOrigin); rawSpores.forEach(collect);
  let T=null;
  if(abs.length>=3){
    const pts=isPortrait?abs.map(p=>[p[1],p[0]]):abs;
    let minx=1/0,miny=1/0,maxx=-1/0,maxy=-1/0;
    pts.forEach(([x,y])=>{minx=Math.min(minx,x);miny=Math.min(miny,y);maxx=Math.max(maxx,x);maxy=Math.max(maxy,y);});
    const bw=Math.max(1,maxx-minx), bh=Math.max(1,maxy-miny);
    // room at the top for the header bar and at the bottom for the legend chips
    const availW=VB.w-2*VB.pad, availH=VB.h-2*VB.pad-(isPortrait?420:150);
    const s=Math.min(availW/bw, availH/bh);
    const ox=(VB.w-bw*s)/2 - minx*s, oy=(VB.h-bh*s)/2 - miny*s + (isPortrait?-40:0);
    T=(p)=>{ const q=isPortrait?[p[1],p[0]]:p; return {x:q[0]*s+ox, y:q[1]*s+oy}; };
  }
  const place=(p)=>{ if(!p)return null; if(isFrac(p)) return {x:p[0]*VB.w,y:p[1]*VB.h}; return T?T(p):null; };
  const cx=VB.w/2, cy=VB.h/2;
  data.trunks.forEach((t,ti)=>{
    const authored=place(t.pos), a=ANCHORS[ti%ANCHORS.length];
    const tp=authored||{x:a[0]*VB.w,y:a[1]*VB.h};
    POS[t.id]=tp;
    const n=t.threads.length, base=Math.atan2(tp.y-cy,tp.x-cx), spread=Math.PI*(isPortrait?0.95:0.85);
    t.threads.forEach((th,i)=>{
      const ap=place(th.pos); if(ap){ POS[th.id]=ap; return; }
      const frac=n===1?0:(i/(n-1))-0.5, ang=base+frac*spread, rad=(isPortrait?215:165)+((i*53)%70);
      POS[th.id]={x:clamp(tp.x+Math.cos(ang)*rad,VB.pad,VB.w-VB.pad), y:clamp(tp.y+Math.sin(ang)*rad,VB.pad+30,VB.h-VB.pad)};
    });
  });
  ORIGIN=place(rawOrigin); SPORES=rawSpores.map(place).filter(Boolean);
}

/* ---------- svg helpers ---------- */
const NS="http://www.w3.org/2000/svg";
function el(name,attrs,parent){ const e=document.createElementNS(NS,name); for(const k in attrs) e.setAttribute(k,attrs[k]); if(parent)parent.appendChild(e); return e; }
function curve(x1,y1,x2,y2,bow){ const mx=(x1+x2)/2,my=(y1+y2)/2,dx=x2-x1,dy=y2-y1,len=Math.hypot(dx,dy)||1; return `M ${x1} ${y1} Q ${mx-dy/len*bow} ${my+dx/len*bow} ${x2} ${y2}`; }
const safeId=(s)=>String(s).replace(/[^a-zA-Z0-9_-]/g,"-");
function txt(tag,cls,content,parent){ const e=document.createElement(tag); if(cls)e.className=cls; if(content!=null)e.textContent=content; if(parent)parent.appendChild(e); return e; }

/* ---------- state ---------- */
let DATA=null, FLAT=[], focusIdx=-1, VIEW="map";
const $=(id)=>document.getElementById(id);
const panel=$("panel"), pinner=$("panelinner"), qindex=$("qindex"), qwrap=$("qwrap");

/* ---------- views ---------- */
function defaultView(){
  const q=PARAMS.get("view"); if(q==="plain"||q==="map") return q;
  try{ const s=localStorage.getItem("careermap.view"); if(s==="plain"||s==="map") return s; }catch(e){}
  return isPortrait ? "plain" : "map";
}
function setView(v, remember){
  VIEW = (v==="plain") ? "plain" : "map";
  document.body.classList.toggle("view-plain", VIEW==="plain");
  document.body.classList.toggle("view-map", VIEW==="map");
  document.querySelectorAll('#top .seg button').forEach(b=>b.setAttribute("aria-pressed", String(b.dataset.view===VIEW)));
  if(remember){ try{ localStorage.setItem("careermap.view", VIEW); }catch(e){} }
  if(VIEW==="plain"){ clearLight(); }
  else if(DATA){ render(DATA); }   // canvas may have been hidden at a different size
}
document.querySelectorAll('#top .seg button').forEach(b=>b.addEventListener("click",()=>{ panel.classList.remove("open"); setView(b.dataset.view, true); }));

/* ---------- render: the canvas ---------- */
function render(data){
  DATA=data; updateMode(); computePositions(data);
  const svg=$("map"); svg.innerHTML="";
  svg.setAttribute("viewBox",`0 0 ${VB.w} ${VB.h}`); svg.setAttribute("preserveAspectRatio","xMidYMid meet");
  const defs=el("defs",{},svg);
  const mkGlow=(id,dev)=>{ const f=el("filter",{id,x:"-150%",y:"-150%",width:"400%",height:"400%"},defs);
    el("feGaussianBlur",{stdDeviation:dev,result:"b"},f); const m=el("feMerge",{},f); el("feMergeNode",{in:"b"},m); el("feMergeNode",{in:"SourceGraphic"},m); };
  mkGlow("glowT",4);
  const gAmbient=el("g",{},svg), gLines=el("g",{},svg), gThrough=el("g",{},svg), gNodes=el("g",{},svg);

  // substrate photo: dark scheme only (light is paper)
  const stage=$("stage");
  const dark = document.documentElement.dataset.scheme==="dark" ||
               (document.documentElement.dataset.scheme!=="light" && window.matchMedia("(prefers-color-scheme: dark)").matches);
  if(dark && data.map.backgroundImageDark){
    stage.classList.add("photo");
    stage.style.backgroundImage=`linear-gradient(rgba(22,24,27,.84), rgba(22,24,27,.9)), url("${encodeURI(data.map.backgroundImageDark)}")`;
  } else { stage.classList.remove("photo"); stage.style.backgroundImage=""; }

  SPORES.forEach(p=>el("circle",{cx:p.x,cy:p.y,r:1.6*SCALE,class:"spore"},gAmbient));
  FLAT=[];
  if(ORIGIN){
    data.trunks.forEach(t=>{ const tp=POS[t.id];
      const pth=el("path",{d:curve(ORIGIN.x,ORIGIN.y,tp.x,tp.y,46),class:"origin-hypha","stroke-width":2.2*SCALE},gLines);
      pth.style.color=cssColor(t.color); });
    el("circle",{cx:ORIGIN.x,cy:ORIGIN.y,r:9*SCALE,class:"origin-dot","stroke-width":1},gAmbient);
  }
  data.trunks.forEach((t,ti)=>{
    const tp=POS[t.id];
    t.threads.forEach(th=>{ const p=POS[th.id];
      const h=el("path",{d:curve(tp.x,tp.y,p.x,p.y,22+((ti*31)%26)),class:"hypha","stroke-width":1.6},gLines); h.style.color=cssColor(t.color); });
    drawNode(gNodes,defs,{id:t.id,label:t.name,years:"",color:t.color,shape:3,r:24,kind:"trunk",glow:true,seed:ti*7+3});
    FLAT.push(t.id);
    t.threads.forEach((th,i)=>{ drawNode(gNodes,defs,{id:th.id,label:th.name,years:th.years,color:t.color,shape:th.shape,r:12,kind:"thread",seed:ti*13+i*5+1}); FLAT.push(th.id); });
  });
  let drawn=0;
  data.throughlines.forEach((tl,i)=>{
    const pts=tl.nodeIds.map(id=>POS[id]).filter(Boolean);
    if(pts.length<2) return;
    let d=`M ${pts[0].x} ${pts[0].y}`;
    for(let k=1;k<pts.length;k++){ const a=pts[k-1],b=pts[k]; d+=` Q ${(a.x+b.x)/2+((i%2?1:-1)*40)} ${(a.y+b.y)/2+40} ${b.x} ${b.y}`; }
    const p=el("path",{d,class:"throughline"+(isDashed(tl.color)?" dashed":""),"data-tl":i,"stroke-width":1.3},gThrough);
    p.style.color=cssColor(tl.color); drawn++;
  });
  svg.dataset.drawn=`${drawn}/${data.throughlines.length}`;
  if(drawn!==data.throughlines.length) badge(`only ${drawn} of ${data.throughlines.length} throughlines could be drawn`);

  buildLegend();
  svg.onclick=(e)=>{ if(e.target.closest(".node"))return; panel.classList.remove("open"); qindex.classList.remove("open"); clearLight(); };
}

function drawNode(parent,defs,o){
  const p=POS[o.id], R=o.r*SCALE;
  const g=el("g",{class:"node",transform:`translate(${p.x},${p.y})`,tabindex:"0",role:"button","aria-label":o.label,"data-id":o.id},parent);
  g.style.color=cssColor(o.color);
  el("rect",{x:-2.2*SCALE,y:-2,width:4.4*SCALE,height:R*0.85,rx:2*SCALE,class:"stem"},g);
  const capD=CAPS[o.shape%CAPS.length](R);
  const cap=el("path",{d:capD,class:"cap","fill-opacity":0.92,transform:`translate(0,${-R*0.15})`},g);
  if(o.glow) cap.setAttribute("filter","url(#glowT)");
  const clipId="clip-"+safeId(o.id); const cp=el("clipPath",{id:clipId},defs); el("path",{d:capD,transform:`translate(0,${-R*0.15})`},cp);
  const gs=el("g",{"clip-path":`url(#${clipId})`},g);
  const n=2+(o.seed%3);
  for(let k=0;k<n;k++){ const sx=(((o.seed*67+k*41)%100)/100-0.5)*R*1.3, sy=-R*(0.35+(((o.seed*29+k*53)%50))/100);
    el("ellipse",{cx:sx,cy:sy,rx:R*0.11,ry:R*0.08,class:"cap-spot"},gs); }
  el("circle",{class:"ring",r:R+9*SCALE},g);
  const fs=(o.kind==="thread"?12*SCALE:14*SCALE);
  el("text",{class:"nlabel",y:R+16*SCALE,"font-size":fs},g).textContent=o.label;
  if(o.years) el("text",{class:"nyears",y:R+29*SCALE,"font-size":10*SCALE},g).textContent=o.years;
  g.addEventListener("click",()=>{ setFocus(FLAT.indexOf(o.id)); openFor(o.id); });
  g.addEventListener("keydown",e=>{ if(e.key==="Enter"||e.key===" "){e.preventDefault();openFor(o.id);} });
}

/* ---------- lookup ---------- */
function findEntity(id){
  for(const t of DATA.trunks){ if(t.id===id) return {kind:"trunk",trunk:t}; for(const th of t.threads) if(th.id===id) return {kind:"thread",trunk:t,thread:th}; }
  return null;
}
function claimsNaming(nodeId){ return DATA.claims.map((c,i)=>({c,i})).filter(({c})=>c.evidence.some(e=>e.node_id===nodeId)); }

/* ---------- panel ---------- */
const panelDrag=$("paneldrag"), desktopPanel=window.matchMedia("(min-width:900px)");
let panelDragState=null;
function clampPanelPosition(left,top){ const gap=14,bottomReserve=110,rect=panel.getBoundingClientRect();
  return {left:Math.min(Math.max(gap,left),Math.max(gap,window.innerWidth-rect.width-gap)), top:Math.min(Math.max(gap,top),Math.max(gap,window.innerHeight-rect.height-bottomReserve))}; }
function placePanel(left,top){ const pos=clampPanelPosition(left,top); panel.style.left=pos.left+"px"; panel.style.top=pos.top+"px"; panel.style.right="auto"; panel.style.bottom="auto"; }
function resetPanelInlinePosition(){ panel.style.left=panel.style.top=panel.style.right=panel.style.bottom=""; }
panelDrag.addEventListener("pointerdown",e=>{ if(!desktopPanel.matches)return; e.preventDefault(); const rect=panel.getBoundingClientRect(); placePanel(rect.left,rect.top);
  panelDragState={dx:e.clientX-rect.left,dy:e.clientY-rect.top}; panel.classList.add("dragging"); panelDrag.setPointerCapture(e.pointerId); });
panelDrag.addEventListener("pointermove",e=>{ if(!panelDragState)return; placePanel(e.clientX-panelDragState.dx,e.clientY-panelDragState.dy); });
function stopPanelDrag(e){ if(!panelDragState)return; panelDragState=null; panel.classList.remove("dragging"); if(e&&panelDrag.hasPointerCapture(e.pointerId)) panelDrag.releasePointerCapture(e.pointerId); }
panelDrag.addEventListener("pointerup",stopPanelDrag); panelDrag.addEventListener("pointercancel",stopPanelDrag);
$("panelclose").addEventListener("click",()=>panel.classList.remove("open"));

function triggerBlock(label,text,parent){ if(!text)return; if(label)txt("div","triglabel",label,parent); txt("div","trigger","“"+text+"”",parent); }
function paragraphs(s,parent){ String(s||"").split(/\n{2,}|\n/).map(x=>x.trim()).filter(Boolean).forEach(par=>txt("p",null,par,parent)); }

function openFor(id){
  const ent=findEntity(id); if(!ent)return;
  const ui=DATA.ui||{}; pinner.innerHTML="";
  pinner.style.color=cssColor(ent.trunk.color);
  const k=txt("div","kicker",null,pinner); txt("span","dot","",k);
  if(ent.kind==="thread"){
    const th=ent.thread;
    txt("span",null,ent.trunk.name,k);
    const h=txt("h2",null,th.name,pinner); h.style.color="var(--ink)";
    txt("div","years",[th.years_full, th.employer].filter(Boolean).join(" · "),pinner);
    if(th.plain_line) txt("div","line",th.plain_line,pinner);
    triggerBlock(ui.nodeTriggerLabel||"",th.trigger,pinner);
    const body=txt("div",null,null,pinner); body.style.color="var(--ink)"; paragraphs(th.detail,body);
    const named=claimsNaming(th.id);
    if(named.length){ txt("h3",null,"Named in",body); const t=txt("div","tags",null,body);
      named.forEach(({c,i})=>{ const b=txt("button","tag act",`${String(i+1).padStart(2,"0")} ${c.sentence}`,t);
        b.addEventListener("click",()=>{ if(VIEW!=="map") setView("map",true); toggleClaim(i); }); }); }
    if(th.keywords.length){ txt("h3",null,"Keywords",body); const t=txt("div","tags",null,body); th.keywords.forEach(w=>txt("span","tag",w,t)); }
    if(th.question_types.length){ txt("h3",null,"Answers questions about",body); const t=txt("div","tags",null,body); th.question_types.forEach(q=>txt("span","tag",q,t)); }
  } else {
    txt("span",null,"Trunk",k);
    const h=txt("h2",null,ent.trunk.name,pinner); h.style.color="var(--ink)";
    triggerBlock(ui.trunkTriggerLabel||"",ent.trunk.trigger,pinner);
    const body=txt("div",null,null,pinner); body.style.color="var(--ink)";
    txt("h3",null,ent.trunk.threads.length+" "+(ui.trunkThreadCountSuffix||"threads"),body);
    const list=txt("div","threadlist",null,body);
    ent.trunk.threads.forEach(th=>{ const b=txt("button",null,th.name+(th.years?"  ·  "+th.years:""),list); b.addEventListener("click",()=>{ setFocus(FLAT.indexOf(th.id)); openFor(th.id); }); });
  }
  panel.classList.add("open");
}
function openTLPanel(i){
  const tl=DATA.throughlines[i]; if(!tl)return; const ui=DATA.ui||{};
  pinner.innerHTML=""; pinner.style.color=cssColor(tl.color);
  const k=txt("div","kicker",null,pinner); txt("span","dot","",k); txt("span",null,"Throughline",k);
  const h=txt("h2",null,tl.name,pinner); h.style.color="var(--ink)";
  const body=txt("div",null,null,pinner); body.style.color="var(--ink)";
  if(tl.plain_reading){ txt("h3",null,"What this pattern means for you",body); txt("p",null,tl.plain_reading,body); }
  triggerBlock(ui.throughlineTriggerLabel||"",tl.trigger,body);
  txt("h3",null,ui.throughlineNodeListLabel||"Crosses",body);
  const list=txt("div","threadlist",null,body);
  tl.nodeIds.forEach((id,idx)=>{ const ent=findEntity(id); if(!ent||ent.kind!=="thread")return;
    const b=txt("button",null,ent.thread.name,list); txt("span","mk",(idx+1<tl.nodeIds.length?(ui.throughlineNextMarker||"→"):(ui.throughlineEndMarker||"⊙")),b);
    b.addEventListener("click",()=>{ setFocus(FLAT.indexOf(id)); openFor(id); }); });
  panel.classList.add("open");
}
function openClaimPanel(i){
  const c=DATA.claims[i]; if(!c)return;
  pinner.innerHTML=""; pinner.style.color="var(--ink)";
  const k=txt("div","kicker",null,pinner); txt("span","dot","",k); txt("span",null,"Proof claim "+String(i+1).padStart(2,"0"),k);
  txt("h2",null,c.sentence,pinner);
  const body=txt("div",null,null,pinner);
  txt("p",null,c.evidence_text,body);
  if(c.link&&c.link.href){ const a=txt("a",null,(c.link.label||"Check it")+" ↗",body); a.href=c.link.href; if(/^https?:/.test(c.link.href)){a.target="_blank";a.rel="noopener";} a.style.cssText="font-family:var(--f-plate);font-size:.74rem;letter-spacing:.06em;text-transform:uppercase"; }
  txt("h3",null,"Where it shows on the map",body);
  const list=txt("div","threadlist",null,body);
  c.evidence.forEach(e=>{ const ent=findEntity(e.node_id); if(!ent)return; const b=txt("button",null,ent.thread.name+"  ·  "+ent.thread.years,list); b.addEventListener("click",()=>{ setFocus(FLAT.indexOf(e.node_id)); openFor(e.node_id); }); });
  panel.classList.add("open");
}

/* ---------- lighting (throughlines and claims share it) ---------- */
let active={kind:null,i:-1};
function clearLight(){
  active={kind:null,i:-1};
  $("stage").classList.remove("tlmode");
  document.querySelectorAll(".throughline.active").forEach(p=>p.classList.remove("active"));
  document.querySelectorAll(".node.lit").forEach(n=>n.classList.remove("lit"));
  document.querySelectorAll(".chip[aria-pressed='true']").forEach(b=>b.setAttribute("aria-pressed","false"));
}
function light(ids, tlIndex, btn){
  $("stage").classList.add("tlmode");
  if(tlIndex!=null){ const p=document.querySelector(`.throughline[data-tl="${tlIndex}"]`); if(p)p.classList.add("active"); }
  ids.forEach(id=>{ const g=document.querySelector(`.node[data-id="${id}"]`); if(g)g.classList.add("lit"); });
  if(btn)btn.setAttribute("aria-pressed","true");
}
function toggleTL(i,btn){
  if(active.kind==="tl"&&active.i===i){ clearLight(); panel.classList.remove("open"); return; }
  clearLight(); active={kind:"tl",i};
  const tl=DATA.throughlines[i]; if(!tl)return;
  light(tl.nodeIds, i, btn||document.querySelector(`#tlbar .chip[data-i="${i}"]`)); openTLPanel(i);
}
function toggleClaim(i,btn){
  if(active.kind==="claim"&&active.i===i){ clearLight(); panel.classList.remove("open"); return; }
  clearLight(); active={kind:"claim",i};
  const c=DATA.claims[i]; if(!c)return;
  light(c.evidence.map(e=>e.node_id), null, btn||document.querySelector(`#claimbar .chip[data-i="${i}"]`)); openClaimPanel(i);
}
function buildLegend(){
  const ui=DATA.ui||{};
  const cb=$("claimbar"); cb.innerHTML="";
  if(DATA.claims.length){ txt("span","lbl","proof",cb);
    DATA.claims.forEach((c,i)=>{ const b=txt("button","chip claimchip",`${String(i+1).padStart(2,"0")} ${c.sentence}`,cb); b.dataset.i=i; b.setAttribute("aria-pressed","false"); b.addEventListener("click",()=>toggleClaim(i,b)); }); }
  const bar=$("tlbar"); bar.innerHTML="";
  txt("span","lbl",ui.legendLabel||"patterns",bar);
  DATA.throughlines.forEach((tl,i)=>{ const b=txt("button","chip",(ui.legendPrefix||"⟿ ")+tl.name,bar); b.dataset.i=i; b.style.setProperty("--chip",cssColor(tl.color)); b.setAttribute("aria-pressed","false"); b.addEventListener("click",()=>toggleTL(i,b)); });
}

/* ---------- plain view ---------- */
function renderPlain(data){
  const id=data.identity||{};
  document.title=data.meta.documentTitle||document.title;
  if(id.name) $("whoname").textContent=id.name;
  $("whotitle").textContent=" · "+(id.title||"Career Map");
  const nav=$("toplinks"); nav.innerHTML="";
  (id.links||[]).forEach(l=>{ const a=txt("a",null,l.label,nav); a.href=l.href; if(/^https?:/.test(l.href)){a.target="_blank";a.rel="noopener";} });

  const ident=$("ident"); ident.innerHTML="";
  txt("h1",null,id.name||"Career Map",ident);
  if(id.line) txt("p","line",id.line,ident);
  const links=txt("div","links",null,ident);
  (id.links||[]).forEach(l=>{ const a=txt("a",null,l.label,links); a.href=l.href; if(/^https?:/.test(l.href)){a.target="_blank";a.rel="noopener";} });

  const cl=$("claims"); cl.innerHTML="";
  $("claimsec").style.display=data.claims.length?"":"none";
  data.claims.forEach((c,i)=>{
    const wrap=txt("div","claim",null,cl);
    const b=txt("button",null,null,wrap); b.setAttribute("aria-expanded","false");
    txt("span","num",String(i+1).padStart(2,"0"),b); txt("span","sent",c.sentence,b); txt("span","arrow","+",b);
    const body=txt("div","body",null,wrap);
    txt("p",null,c.evidence_text,body);
    const chips=txt("div","chips",null,body);
    c.evidence.forEach(e=>{ const ent=findEntity(e.node_id); if(!ent)return;
      const ch=txt("button","nodechip",ent.thread.name,chips); ch.style.color=cssColor(ent.trunk.color);
      ch.addEventListener("click",()=>{ setFocus(FLAT.indexOf(e.node_id)); openFor(e.node_id); }); });
    if(c.link&&c.link.href){ const a=txt("a",null,c.link.label||"Check it",chips); a.href=c.link.href; if(/^https?:/.test(c.link.href)){a.target="_blank";a.rel="noopener";} }
    const show=txt("button","nodechip","show on the map",chips); show.style.color="var(--ink-soft)";
    show.addEventListener("click",()=>{ setView("map",true); toggleClaim(i); window.scrollTo(0,0); });
    b.addEventListener("click",()=>{ const open=wrap.hasAttribute("open"); wrap.toggleAttribute("open",!open); b.setAttribute("aria-expanded",String(!open)); b.querySelector(".arrow").textContent=open?"+":"−"; });
  });

  const cards=$("tlcards"); cards.innerHTML="";
  data.throughlines.forEach((tl,i)=>{
    const c=txt("div","card",null,cards); c.style.color=cssColor(tl.color);
    txt("h3",null,tl.name,c);
    if(tl.plain_reading) txt("p",null,tl.plain_reading,c);
    txt("p","trig","“"+tl.trigger+"”",c);
    const n=tl.nodeIds.map(id=>findEntity(id)).filter(Boolean).map(e=>e.thread.name);
    const small=txt("p",null,n.join(" → "),c); small.style.cssText="font-size:.8rem;color:var(--ink-soft);flex:0";
    const b=txt("button",null,"Show on the map",c); b.addEventListener("click",()=>{ setView("map",true); toggleTL(i); window.scrollTo(0,0); });
  });

  const tlist=$("timeline"); tlist.innerHTML="";
  const byId={}; data.trunks.forEach(t=>t.threads.forEach(th=>byId[th.id]={th,t}));
  data.chronology.forEach(r=>{
    const e=byId[r.id]; if(!e)return;
    const row=txt("button","tl",null,tlist);
    txt("span","yr",e.th.years_full,row);
    const d=txt("div",null,null,row);
    const role=txt("div","role",e.th.name,d); role.style.color=cssColor(e.t.color);
    txt("div","org",[e.th.employer,e.th.kind].filter(Boolean).join(" · "),d);
    if(e.th.plain_line) txt("div","note",e.th.plain_line,d);
    row.addEventListener("click",()=>{ setFocus(FLAT.indexOf(r.id)); openFor(r.id); });
  });

  const f=$("plainfoot"); f.innerHTML="";
  const a=txt("a",null,"The proof page has the short version →",f); a.href="../";
  const q=txt("button","tbtn","Question index",f); q.addEventListener("click",openQ);
}

/* ---------- question index ---------- */
function buildQIndex(){
  qwrap.innerHTML="";
  txt("h2",null,"Question index",qwrap);
  txt("div","sub","“tell me about a time…” → the nodes that answer it",qwrap);
  const map={};
  DATA.trunks.forEach(t=>t.threads.forEach(th=>th.question_types.forEach(q=>{ (map[q]=map[q]||[]).push({th,t}); })));
  const order=DATA.meta.question_taxonomy||[];
  const keys=Object.keys(map).sort((a,b)=>{ const ia=order.indexOf(a), ib=order.indexOf(b); return (ia<0?99:ia)-(ib<0?99:ib) || a.localeCompare(b); });
  if(!keys.length){ txt("p",null,"No question tags yet.",qwrap); return; }
  keys.forEach(q=>{
    const sec=txt("div","arch",null,qwrap); txt("h3",null,"“Tell me about … "+q+"”",sec);
    map[q].forEach(({th,t})=>{ const b=txt("button",null,null,sec); b.style.color=cssColor(t.color);
      txt("span","dot","",b); const s=txt("span",null,th.name,b); s.style.color="var(--ink)";
      b.addEventListener("click",()=>{ qindex.classList.remove("open"); setFocus(FLAT.indexOf(th.id)); openFor(th.id); }); });
  });
}
function openQ(){ buildQIndex(); qindex.classList.add("open"); }
$("qbtn").addEventListener("click",openQ);
$("qclose").addEventListener("click",()=>qindex.classList.remove("open"));

/* ---------- keyboard ---------- */
function setFocus(i){
  if(i<0||i>=FLAT.length)return; focusIdx=i;
  document.querySelectorAll(".node.focused").forEach(n=>n.classList.remove("focused"));
  const g=document.querySelector(`.node[data-id="${FLAT[i]}"]`); if(g){ g.classList.add("focused"); if(VIEW==="map") g.focus({preventScroll:true}); }
}
document.addEventListener("keydown",e=>{
  if(e.target.tagName==="INPUT"||e.target.tagName==="TEXTAREA"||!DATA)return;
  if(e.key==="Escape"){ panel.classList.remove("open"); qindex.classList.remove("open"); clearLight(); return; }
  const key=e.key.toLowerCase();
  if(key==="q"){ if(qindex.classList.contains("open")) qindex.classList.remove("open"); else openQ(); return; }
  if(key==="p"){ panel.classList.remove("open"); setView(VIEW==="map"?"plain":"map", true); return; }
  if(VIEW!=="map") return;
  if(/^[1-9]$/.test(e.key)){ const t=DATA.trunks[Number(e.key)-1]; if(t){ setFocus(FLAT.indexOf(t.id)); openFor(t.id); } return; }
  if(e.key==="ArrowRight"){ e.preventDefault(); setFocus(Math.min(FLAT.length-1,focusIdx+1)); }
  if(e.key==="ArrowLeft"){ e.preventDefault(); setFocus(Math.max(0,focusIdx-1)); }
  if(e.key==="Enter"){ if(focusIdx<0) setFocus(0); openFor(FLAT[focusIdx]); }
});

/* ---------- resize ---------- */
let resizeTimer=null;
window.addEventListener("resize",()=>{
  if(!desktopPanel.matches) resetPanelInlinePosition();
  else if(panel.style.left&&panel.style.top) placePanel(parseFloat(panel.style.left),parseFloat(panel.style.top));
  clearTimeout(resizeTimer);
  resizeTimer=setTimeout(()=>{ if(!DATA)return; const was=isPortrait; updateMode();
    if(isPortrait!==was && VIEW==="map"){ panel.classList.remove("open"); clearLight(); render(DATA); } },200);
});

/* ---------- debug probe (headless checks): ?debug=1 ---------- */
function debugOverflow(){
  if(PARAMS.get("debug")!=="1") return;
  const w=window.innerWidth, bad=[];
  document.querySelectorAll("body *").forEach(e=>{ const r=e.getBoundingClientRect(); if(r.width>0 && r.right>w+1 && getComputedStyle(e).position!=="fixed") bad.push(e.tagName.toLowerCase()+(e.id?"#"+e.id:"")+(e.className&&typeof e.className==="string"?"."+e.className.split(" ")[0]:"")+"="+Math.round(r.right)); });
  badge(`scrollWidth=${document.documentElement.scrollWidth} innerWidth=${w} :: ${bad.slice(0,12).join(" ")}`);
}

/* ---------- boot ---------- */
function badge(msg){ const b=$("databadge"); b.textContent=msg; b.style.display="block"; }
fetch("career.json",{cache:"no-store"})
  .then(r=>{ if(!r.ok) throw new Error("career.json HTTP "+r.status); return r.json(); })
  .then(raw=>{ const data=normalize(raw); DATA=data; renderPlain(data); render(data); setView(defaultView(), false); debugOverflow(); })
  .catch(err=>{ console.error(err); badge("Could not load the map: "+err.message); setView("plain",false);
    const ident=$("ident"); ident.innerHTML=""; txt("h1",null,"Orpita Das",ident);
    const p=txt("p","line","The career map did not load. The proof page and the résumé are one level up.",ident);
    const a=txt("a",null,"← odas.github.io",p); a.href="../"; });
